# Generated by Django 5.1.5 on 2025-01-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_calculation_markup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='markup',
        ),
    ]
