# Generated by Django 5.1.5 on 2025-02-20 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_calculationsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationsnapshot',
            name='calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='trades.calculation'),
        ),
        migrations.CreateModel(
            name='CalculationSnapshotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trades.calculationsnapshot')),
            ],
        ),
    ]
