# Generated by Django 5.1.5 on 2025-02-21 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_alter_calculationsnapshot_calculation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculationsnapshot',
            old_name='frozen_total_price',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='calculationsnapshot',
            old_name='frozen_total_price_with_markup',
            new_name='total_price_with_markup',
        ),
    ]
