# Generated by Django 5.1.5 on 2025-02-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_rename_frozen_total_price_calculationsnapshot_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationsnapshot',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='calculationsnapshot',
            name='total_price_with_markup',
        ),
        migrations.AddField(
            model_name='calculationsnapshot',
            name='frozen_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calculationsnapshot',
            name='frozen_total_price_with_markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
