# Generated by Django 5.1.5 on 2025-01-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_remove_calculation_markup'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
