# Generated by Django 5.1.5 on 2025-01-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_calculation_markup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationitem',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
