# Generated by Django 5.2.7 on 2025-11-22 17:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_alter_calculation_user_nullable'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='calculationitem',
            name='calc_item_calc_idx',
        ),
        migrations.RenameIndex(
            model_name='calculation',
            new_name='trades_calc_user_id_545568_idx',
            old_name='calc_user_date_idx',
        ),
        migrations.RenameIndex(
            model_name='pricehistory',
            new_name='trades_pric_item_id_abee11_idx',
            old_name='price_hist_item_idx',
        ),
        migrations.AlterField(
            model_name='calculation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='calculationitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='calculationsnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Цена должна быть больше нуля')]),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='calculation',
            index=models.Index(fields=['-created_at'], name='trades_calc_created_c0f7e0_idx'),
        ),
        migrations.AddIndex(
            model_name='calculationsnapshot',
            index=models.Index(fields=['calculation', '-created_at'], name='trades_calc_calcula_284251_idx'),
        ),
        migrations.AddIndex(
            model_name='calculationsnapshot',
            index=models.Index(fields=['-created_at'], name='trades_calc_created_e9b539_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='trades_item_name_43adc6_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['-changed_at'], name='trades_pric_changed_cfd8c4_idx'),
        ),
    ]
