# Generated by Django 5.1.5 on 2025-01-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0009_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='price_step',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=5),
        ),
    ]
