# Generated by Django 5.1.5 on 2025-01-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0010_usersettings_price_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='markup_step',
            field=models.PositiveIntegerField(default=2, verbose_name='Знаков после запятой для наценки'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='decimal_places_percentage',
            field=models.PositiveIntegerField(default=2, verbose_name='Знаков после запятой для наценки'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='decimal_places_price',
            field=models.PositiveIntegerField(default=2, verbose_name='Знаков после запятой для цены'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='price_step',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=5, verbose_name='Шаг изменения цены'),
        ),
    ]
