# Generated by Django 5.1.5 on 2025-02-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0014_remove_customuser_role_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
